#!/bin/sh

# $1 - PID of process to dump memory of
target_pid="$1"

# $2 - optional - file name for dump

nums_only=$(echo "$target_pid" | grep -v '[^0-9]')
if [ -z "$target_pid" ] || [ "$nums_only" != "$target_pid" ] || ! [ "$target_pid" -gt 0 ]; then
  echo "Incorrect PID: '$target_pid'"
  exit 1
  fi

if ! [ -f "/proc/$target_pid/maps" ]; then
  echo "/proc/$target_pid/maps: No such file or directory"
  exit 1
  fi

maps=$(cat /proc/"$target_pid"/maps)

[ "$maps" ] || { echo 'No maps to select from' && exit 0; }

map=$(echo "$maps" | percol)
percol_exit="$?"
if [ "$percol_exit" -gt 0 ]; then
  exit "$percol_exit"
  fi

filename="$target_pid"
map_name=$(echo "$map" | awk '{print $6}' | sed -e 's|/|--|g')
[ "$map_name" ] && filename="$filename.$map_name"
filename="$filename.mem"

if [ -n "$2" ]; then
  filename="$2"
  fi

echo "Writing memory to file: '$filename'"

if [ -f "$filename" ]; then
  printf "Will overwrite $filename, press Enter to continue"
  tty_settings=$(stty -g)
  cleanup () {
    stty "$tty_settings"
    }
  trap cleanup 1 2 3 6 14 15
  stty -echo
  read -r key # $key is never used, but must be given to read because POSIX
  cleanup
  echo
  fi

IFS=' -' read -r start stop _ <<EOF
$map
EOF

gdb \
  </dev/null >/dev/null -nx -batch \
  -ex 'set pagination off' -ex 'set height 0' -ex 'set width 0' \
  -ex "attach $target_pid" -ex "dump memory $filename 0x$start 0x$stop" \
  -ex 'detach' -ex 'quit'
